/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.disabledmallis.java2cpp;

public class Main {
    public static void main(String[] args) {
        Log.Out("Java2Cpp");
    }
}
